FROM mcr.microsoft.com/devcontainers/typescript-node:0-18

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
      libasound2 \
      libatk1.0-0 \
      libatk-bridge2.0-0 \
      libatspi2.0-0 \
      libcups2 libdrm2 \
      libdbus-1-3 \
      libgbm1 \
      libnss3 \
      libxcomposite1 \
      libxdamage1 \
      libxfixes3 \
      libxkbcommon0 \
      libxrandr2
